---
- hosts: glassfish
  tasks:
    - name: Add apt repositories
      apt_repository:
        repo: "ppa:webupd8team/java"

    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes

    - name: Install required packages
      apt:
        name: "{{ required_packages }}"
        state: present

    - name: Create Glassfish Directory
      file:
        path: "{{ glassfish_directory }}"
        state: directory
        mode: "0755"

    - name: Download & decompress Glassfish server
      unarchive:
        src: "{{ glassfish_source }}"
        dest: "{{ glassfish_directory }}"
        remote_src: yes

    - name: Configure Glassfish for systemd
      shell: |
        cat << EOF > "/lib/systemd/system/{{ glassfish_systemd_service_name }}.service"
        [Unit]
        Description = GlassFish Server
        After = syslog.target network.target
        
        [Service]
        ExecStart={{ glassfish_directory }}/glassfish5/bin/asadmin start-domain
        ExecReload={{ glassfish_directory }}/glassfish5/bin/asadmin restart-domain
        ExecStop={{ glassfish_directory }}/glassfish5/bin/asadmin stop-domain
        Type = forking
        
        [Install]
        WantedBy = multi-user.target
        EOF
      args:
        creates: "/lib/systemd/system/{{ glassfish_systemd_service_name }}.service"

    - name: Create AppDynamics Java Agent Installer Directory
      file:
        path: "{{ java_agent_directory }}" 
        state: directory
        mode: "0755"

    - name: Download & decompress AppDynamics Java Agent
      unarchive:
        src: "{{ java_agent_source }}"
        dest: "{{ java_agent_directory }}"
        remote_src: yes

    - name: Create AppDynamics Agent Log Directory for node
      file:
        path: "{{ java_agent_directory }}/{{ java_agent_version_directory }}/logs/{{ node_name }}"
        state: directory
        mode: "0755"

    - name: Write controller host to configuration file
      xml:
        path: "{{ java_agent_directory }}/{{ java_agent_version_directory }}/conf/controller-info.xml"
        xpath: /controller-info/controller-host
        value: "{{ controller_host }}"

    - name: Write controller port to configuration file
      xml:
        path: "{{ java_agent_directory }}/{{ java_agent_version_directory }}/conf/controller-info.xml"
        xpath: /controller-info/controller-port
        value: "{{ controller_port }}"

    - name: Write application name to configuration file
      xml:
        path: "{{ java_agent_directory }}/{{ java_agent_version_directory }}/conf/controller-info.xml"
        xpath: /controller-info/application-name
        value: "{{ application_name }}"

    - name: Write tier name to configuration file
      xml:
        path: "{{ java_agent_directory }}/{{ java_agent_version_directory }}/conf/controller-info.xml"
        xpath: /controller-info/tier-name
        value: "{{ tier_name }}"

    - name: Write node name to configuration file
      xml:
        path: "{{ java_agent_directory }}/{{ java_agent_version_directory }}/conf/controller-info.xml"
        xpath: /controller-info/node-name
        value: "{{ node_name }}"

    - name: Write account name to configuration file
      xml:
        path: "{{ java_agent_directory }}/{{ java_agent_version_directory }}/conf/controller-info.xml"
        xpath: /controller-info/account-name
        value: "{{ account_name }}"

    - name: Write account access key to configuration file
      xml:
        path: "{{ java_agent_directory }}/{{ java_agent_version_directory }}/conf/controller-info.xml"
        xpath: /controller-info/account-access-key
        value: "{{ account_access_key }}"

    - name: Create Database Agent Directory
      file:
        path: "{{ database_agent_directory }}"
        state: directory
        mode: "0755"

    - name: Download & decompress AppDynamics Database Agent
      unarchive:
        src: "{{ database_agent_source }}"
        dest: "{{ database_agent_directory }}"
        remote_src: yes

    - name: Write controller host to Database Agent configuration file
      xml:
        path: "{{ database_agent_directory }}/conf/controller-info.xml"
        xpath: /controller-info/controller-host
        value: "{{ controller_host }}"

    - name: Write controller port to Database Agent configuration file
      xml:
        path: "{{ database_agent_directory }}/conf/controller-info.xml"
        xpath: /controller-info/controller-port
        value: "{{ controller_port }}"

    - name: Write application name to Database Agent configuration file
      xml:
        path: "{{ database_agent_directory }}/conf/controller-info.xml"
        xpath: /controller-info/application-name
        value: "{{ application_name }}"

    - name: Write tier name to Database Agent configuration file
      xml:
        path: "{{ database_agent_directory }}/conf/controller-info.xml"
        xpath: /controller-info/tier-name
        value: "{{ tier_name }}"

    - name: Write node name to Database Agent configuration file
      xml:
        path: "{{ database_agent_directory }}/conf/controller-info.xml"
        xpath: /controller-info/node-name
        value: "{{ node_name }}"

    - name: Write account name to Database Agent configuration file
      xml:
        path: "{{ database_agent_directory }}/conf/controller-info.xml"
        xpath: /controller-info/account-name
        value: "{{ account_name }}"

    - name: Write account access key to configuration file
      xml:
        path: "{{ database_agent_directory }}/conf/controller-info.xml"
        xpath: /controller-info/account-access-key
        value: "{{ account_access_key }}"

    - name: Configure Db Agent for systemd
      shell: |
        cat << EOF > "/lib/systemd/system/{{ database_agent_systemd_service_name }}.service"
        [Unit]
        Description=AppDynamics DB Agent
        
        [Service]
        ExecStart={{ database_agent_directory }}/start-dbagent
        ExecReload=/bin/kill -HUP $MAINPID
        KillMode=process
        Restart=on-failure
        RestartPreventExitStatus=255
        
        [Install]
        WantedBy=multi-user.target
        Alias={{ database_agent_systemd_service_name }}.service
        EOF
      args:
        creates: "/lib/systemd/system/{{ database_agent_systemd_service_name }}.service"

    - name: Create Machine Agent Directory
      file:
        path: "{{ machine_agent_directory }}"
        state: directory
        mode: "0755"

    - name: Download & decompress AppDynamics Machine Agent
      unarchive:
        src: "{{ machine_agent_source }}"
        dest: "{{ machine_agent_directory }}"
        remote_src: yes

    - name: Configure Machine Agent in systemd
      shell: |
        cat << EOF > "/lib/systemd/system/{{ machine_agent_systemd_service_name }}.service"
        [Unit]
        Description=AppDynamics Machine Agent

        [Service]
        ExecStart={{ machine_agent_directory }}/jre/bin/java -jar {{ machine_agent_directory }}/machineagent.jar
        KillMode=control-group
        Restart=on-failure
        RestartPreventExitStatus=255
        Type=simple
        TimeoutSec=900

        [Install]
        WantedBy=multi-user.target
        Alias={{ machine_agent_systemd_service_name}}.service
        EOF
      args:
        creates: "/lib/systemd/system/{{ machine_agent_systemd_service_name }}.service"

    - name: Create Network Agent Directory
      file:
        path: "{{ netviz_agent_directory }}"
        state: directory
        mode: "0755"

    - name: Download & decompress AppDynamics Network Agent
      unarchive:
        src: "{{ netviz_agent_source }}"
        dest: "{{ netviz_agent_directory }}"
        remote_src: yes

    - name: Install AppDynamics Network Agent
      shell: |
        bash -c "{{ netviz_agent_directory }}/install.sh"
        touch "{{ netviz_agent_directory }}/netviz.installed"
      args:
        creates: "{{ netviz_agent_directory }}/netviz.installed"

    - name: Configure Network Agent in systemd
      shell: |
        cat << EOF > "/lib/systemd/system/{{ netviz_agent_systemd_service_name }}.service"
        [Unit]
        Description=AppDynamics Network Agent
        After=network.target

        [Service]
        ExecStart={{ netviz_agent_directory }}/bin/start.sh
        KillMode=control-group
        Restart=always
        RestartPreventExitStatus=255
        Type=forking
        TimeoutSec=900

        [Install]
        WantedBy=multi-user.target
        Alias={{ netviz_agent_systemd_service_name}}.service
        EOF
      args:
        creates: "/lib/systemd/system/{{ netviz_agent_systemd_service_name }}.service"

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Start Glassfish server
      service:
        name: "{{ glassfish_systemd_service_name }}"
        enabled: true
        state: restarted

    - name: Start Machine Agent service
      service:
        name: "{{ machine_agent_systemd_service_name }}"
        enabled: true
        state: restarted

    - name: Start Network Agent service
      service:
        name: "{{ netviz_agent_systemd_service_name }}"
        enabled: true
        state: restarted

    - name: Start Database Agent service
      service:
        name: "{{ database_agent_systemd_service_name }}"
        enabled: true
        state: restarted
